### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by himanikohli** [eml-eda/mixprec-pruning#1]
i have been trying to run the icl_PIT_training file, but it shows an error that module not found: python_benchmark in line "import pytorch_benchmarks.image_classification as icl". could you please help with this error? is the package have other definition?

**Comment by bmots** [comment]
Dear @himanikohli,
thank you for your feedback. 
A `requirements.txt` file with the list of required packages has been uploaded. Installing the reported dependencies should fix the error.
